modLoader = "javafml"
loaderVersion = "[61,)"
issueTrackerURL = "https://github.com/Potion-Studios/Nether-Descent/issues"
license = "All Rights Reserved"

[[mods]]
modId = "netherdescent"
version = "${version}"
displayName = "Nether Descent"
logoFile = "netherdescent.png"
authors = "Joseph T. McQuigg (JT122406), AOCAWOL"
description = '''
Nether Descent is a brand new nether biome mod by the Potion Studios team, truly an adventure like no other awaits you with new biomes, mobs, blocks, items, and more!
'''
displayURL="https://potionstudios.net/"

[[dependencies.netherdescent]]
modId = "forge"
mandatory = true
versionRange = "[61.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.netherdescent]]
modId = "minecraft"
mandatory = true
versionRange = "[26.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.netherdescent]]
modId = "ohthetreesyoullgrow"
mandatory = true
versionRange = "[10.1.1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.netherdescent]]
modId = "terrablender"
mandatory = false
versionRange = "[26.1.2.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.netherdescent]]
modId = "biolith"
mandatory = false
versionRange = "[3.6.0-alpha.9,)"
ordering = "AFTER"
side = "BOTH"
