modLoader = "javafml"
loaderVersion = "[52,)"
issueTrackerURL = "https://github.com/Potion-Studios/Nether-Descent/issues"
license = "All Rights Reserved"

[[mods]]
modId = "netherdescent"
version = "${version}"
displayName = "Nether Descent"
logoFile = "netherdescent.png"
authors = "Joseph T. McQuigg (JT122406), AOCAWOL"
description = '''
'''
displayURL="https://potionstudios.net/"

[[dependencies.netherdescent]]
modId = "forge"
mandatory = true
versionRange = "[52.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.netherdescent]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.netherdescent]]
modId = "terrablender"
mandatory = true
versionRange = "[4.1.0.0,)"
ordering = "AFTER"
side = "BOTH"