org.gradle.jvmargs=-Xmx2G

minecraft_version=26.3

archives_base_name=Nether-Descent
mod_version=1.0.10-SNAPSHOT
maven_group=net.potionstudios

fabric_loader_version=0.19.5
fabric_api_version=0.161.0

forge_version=66.0.9

neoforge_version=26.3.0.48-beta

devauth_version=1.2.2

terrablender_version=26.3.0.0.8
biolith_version=3.8.0-beta.1
lithostitched_version=2.0.4
ohthetreesyoullgrow_version=12.0.1

WTHIT=20.0.0
badPackets=0.12.2