org.gradle.jvmargs=-Xmx2G

minecraft_version=1.21.4

archives_base_name=Nether-Descent
mod_version=1.0.8-SNAPSHOT
maven_group=net.potionstudios

fabric_loader_version=0.19.3
fabric_api_version=0.119.4

forge_version=54.1.18

neoforge_version=21.4.157

parchment=2025.03.23

devauth_version=1.2.2

terrablender_version=4.3.0.2
biolith_version=3.2.14
#lithostitched_version=1.4.5
ohthetreesyoullgrow_version=6.1.0

WTHIT=14.6.1
badPackets=0.8.2