org.gradle.jvmargs=-Xmx2G

minecraft_version=26.1.2

archives_base_name=Nether-Descent
mod_version=1.0.5-SNAPSHOT
maven_group=net.potionstudios

fabric_loader_version=0.19.3
fabric_api_version=0.155.2

forge_version=64.0.11

neoforge_version=26.1.2.81

devauth_version=1.2.2

terrablender_version=26.1.2.0.3
biolith_version=3.6.0-alpha.9
lithostitched_version=1.7.13
ohthetreesyoullgrow_version=10.1.1

WTHIT=19.0.1
badPackets=0.12.2