package net.potionstudios.netherdescent.world.level.block;

import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.level.block.Block;
import net.potionstudios.netherdescent.NetherDescent;

public class NetherDescentBlockIds {

    public static final ResourceKey<Block> BLUE_NETHERRACK = createKey("blue_netherrack");
    public static final ResourceKey<Block> BLUE_NETHER_GOLD_ORE = createKey("blue_nether_gold_ore");
    public static final ResourceKey<Block> BLUE_NETHER_QUARTZ_ORE = createKey("blue_nether_quartz_ore");
    public static final ResourceKey<Block> BLUE_NETHER_BRICKS = createKey("blue_nether_bricks");
    public static final ResourceKey<Block> BLUE_NETHER_BRICK_STAIRS = createKey("blue_nether_brick_stairs");
    public static final ResourceKey<Block> BLUE_NETHER_BRICK_SLAB = createKey("blue_nether_brick_slab");
    public static final ResourceKey<Block> BLUE_NETHER_BRICK_WALL = createKey("blue_nether_brick_wall");
    public static final ResourceKey<Block> BLUE_NETHER_BRICK_FENCE = createKey("blue_nether_brick_fence");
    public static final ResourceKey<Block> MOSSY_BLUE_NETHER_BRICKS = createKey("mossy_blue_nether_bricks");
    public static final ResourceKey<Block> MOSSY_BLUE_NETHER_BRICK_STAIRS = createKey("mossy_blue_nether_brick_stairs");
    public static final ResourceKey<Block> MOSSY_BLUE_NETHER_BRICK_SLAB = createKey("mossy_blue_nether_brick_slab");
    public static final ResourceKey<Block> MOSSY_BLUE_NETHER_BRICK_WALL = createKey("mossy_blue_nether_brick_wall");
    public static final ResourceKey<Block> CHISELED_BLUE_NETHER_BRICKS = createKey("chiseled_blue_nether_bricks");
    public static final ResourceKey<Block> CRACKED_BLUE_NETHER_BRICKS = createKey("cracked_blue_nether_bricks");

    public static final ResourceKey<Block> WAILING_NYLIUM = createKey("wailing_nylium");
    public static final ResourceKey<Block> WAILING_VINES = createKey("wailing_vines");
    public static final ResourceKey<Block> WAILING_VINES_PLANT = createKey("wailing_vines_plant");
    public static final ResourceKey<Block> WAILING_GRASS = createKey("wailing_grass");
    public static final ResourceKey<Block> WAILING_GILLS = createKey("wailing_gills");
    public static final ResourceKey<Block> WAILING_BULB_BLOSSOM = createKey("wailing_bulb_blossom");
    public static final ResourceKey<Block> WAILING_WART_BLOCK = createKey("wailing_wart_block");
    public static final ResourceKey<Block> WAILING_STEM = createKey("wailing_stem");
    public static final ResourceKey<Block> WAILING_HYPHAE = createKey("wailing_hyphae");
    public static final ResourceKey<Block> STRIPPED_WAILING_STEM = createKey("stripped_wailing_stem");
    public static final ResourceKey<Block> STRIPPED_WAILING_HYPHAE = createKey("stripped_wailing_hyphae");
    public static final ResourceKey<Block> WAILING_PLANKS = createKey("wailing_planks");
    public static final ResourceKey<Block> WAILING_STAIRS = createKey("wailing_stairs");
    public static final ResourceKey<Block> WAILING_SLAB = createKey("wailing_slab");
    public static final ResourceKey<Block> WAILING_FENCE = createKey("wailing_fence");
    public static final ResourceKey<Block> WAILING_FENCE_GATE = createKey("wailing_fence_gate");
    public static final ResourceKey<Block> WAILING_DOOR = createKey("wailing_door");
    public static final ResourceKey<Block> WAILING_TRAPDOOR = createKey("wailing_trapdoor");
    public static final ResourceKey<Block> WAILING_PRESSURE_PLATE = createKey("wailing_pressure_plate");
    public static final ResourceKey<Block> WAILING_BUTTON = createKey("wailing_button");
    public static final ResourceKey<Block> WAILING_FUNGUS = createKey("wailing_fungus");
    public static final ResourceKey<Block> POTTED_WAILING_FUNGUS = createKey("potted_wailing_fungus");
    public static final ResourceKey<Block> WAILING_BOOKSHELF = createKey("wailing_bookshelf");
    public static final ResourceKey<Block> WAILING_CRAFTING_TABLE = createKey("wailing_crafting_table");
    public static final ResourceKey<Block> WAILING_SIGN = createKey("wailing_sign");
    public static final ResourceKey<Block> WAILING_WALL_SIGN = createKey("wailing_wall_sign");
    public static final ResourceKey<Block> WAILING_HANGING_SIGN = createKey("wailing_hanging_sign");
    public static final ResourceKey<Block> WAILING_WALL_HANGING_SIGN = createKey("wailing_wall_hanging_sign");

    public static final ResourceKey<Block> EMBUR_NYLIUM = createKey("embur_nylium");
    public static final ResourceKey<Block> EMBUR_GEL_BLOCK = createKey("embur_gel_block");
    public static final ResourceKey<Block> EMBUR_GEL_VINES = createKey("embur_gel_vines");
    public static final ResourceKey<Block> EMBUR_GEL_VINES_PLANT = createKey("embur_gel_vines_plant");
    public static final ResourceKey<Block> EMBUR_SPROUTS = createKey("embur_sprouts");
    public static final ResourceKey<Block> EMBUR_LILY = createKey("embur_lily");
    public static final ResourceKey<Block> EMBUR_ROOTS = createKey("embur_roots");
    public static final ResourceKey<Block> POTTED_EMBUR_ROOTS = createKey("potted_embur_roots");
    public static final ResourceKey<Block> TALL_EMBUR_ROOTS = createKey("tall_embur_roots");
    public static final ResourceKey<Block> EMBUR_CAVE_MOSS = createKey("embur_cave_moss");
    public static final ResourceKey<Block> EMBUR_MOSS_BLOCK = createKey("embur_moss_block");
    public static final ResourceKey<Block> EMBUR_MOSS_CARPET = createKey("embur_moss_carpet");
    public static final ResourceKey<Block> EMBUR_HANGING_MOSS = createKey("embur_hanging_moss");
    public static final ResourceKey<Block> EMBUR_PEDU = createKey("embur_pedu");
    public static final ResourceKey<Block> EMBUR_HYPHAE = createKey("embur_hyphae");
    public static final ResourceKey<Block> STRIPPED_EMBUR_PEDU = createKey("stripped_embur_pedu");
    public static final ResourceKey<Block> STRIPPED_EMBUR_HYPHAE = createKey("stripped_embur_hyphae");
    public static final ResourceKey<Block> EMBUR_PLANKS = createKey("embur_planks");
    public static final ResourceKey<Block> EMBUR_STAIRS = createKey("embur_stairs");
    public static final ResourceKey<Block> EMBUR_SLAB = createKey("embur_slab");
    public static final ResourceKey<Block> EMBUR_FENCE = createKey("embur_fence");
    public static final ResourceKey<Block> EMBUR_FENCE_GATE = createKey("embur_fence_gate");
    public static final ResourceKey<Block> EMBUR_DOOR = createKey("embur_door");
    public static final ResourceKey<Block> EMBUR_TRAPDOOR = createKey("embur_trapdoor");
    public static final ResourceKey<Block> EMBUR_PRESSURE_PLATE = createKey("embur_pressure_plate");
    public static final ResourceKey<Block> EMBUR_BUTTON = createKey("embur_button");
    public static final ResourceKey<Block> EMBUR_WART = createKey("embur_wart");
    public static final ResourceKey<Block> POTTED_EMBUR_WART = createKey("potted_embur_wart");
    public static final ResourceKey<Block> EMBUR_BOOKSHELF = createKey("embur_bookshelf");
    public static final ResourceKey<Block> EMBUR_CRAFTING_TABLE = createKey("embur_crafting_table");
    public static final ResourceKey<Block> EMBUR_SIGN = createKey("embur_sign");
    public static final ResourceKey<Block> EMBUR_WALL_SIGN = createKey("embur_wall_sign");
    public static final ResourceKey<Block> EMBUR_HANGING_SIGN = createKey("embur_hanging_sign");
    public static final ResourceKey<Block> EMBUR_WALL_HANGING_SIGN = createKey("embur_wall_hanging_sign");

    public static final ResourceKey<Block> TALL_ARISIAN_SPROUTS = createKey("tall_arisian_sprouts");
    public static final ResourceKey<Block> ARISIAN_SPROUTS = createKey("arisian_sprouts");
    public static final ResourceKey<Block> POTTED_ARISIAN_SPROUTS = createKey("potted_arisian_sprouts");
    public static final ResourceKey<Block> ARISIAN_MOSS_BLOCK = createKey("arisian_moss_block");
    public static final ResourceKey<Block> ARISIAN_MOSS_CARPET = createKey("arisian_moss_carpet");
    public static final ResourceKey<Block> ARISIAN_TANGLE_ROOTS = createKey("arisian_tangle_roots");
    public static final ResourceKey<Block> ARISIAN_TANGLE_ROOTS_PLANT = createKey("arisian_tangle_roots_plant");
    public static final ResourceKey<Block> ARISIAN_BLOSSOM = createKey("arisian_blossom");
    public static final ResourceKey<Block> POTTED_ARISIAN_BLOSSOM = createKey("potted_arisian_blossom");
    public static final ResourceKey<Block> ARISIAN_BRANCH = createKey("arisian_branch");
    public static final ResourceKey<Block> TALL_ARISIAN_DANDELIONS = createKey("tall_arisian_dandelions");
    public static final ResourceKey<Block> ARISIAN_DANDELIONS = createKey("arisian_dandelions");
    public static final ResourceKey<Block> ARISIAN_LOG = createKey("arisian_log");
    public static final ResourceKey<Block> ARISIAN_WOOD = createKey("arisian_wood");
    public static final ResourceKey<Block> STRIPPED_ARISIAN_LOG = createKey("stripped_arisian_log");
    public static final ResourceKey<Block> STRIPPED_ARISIAN_WOOD = createKey("stripped_arisian_wood");
    public static final ResourceKey<Block> ARISIAN_PLANKS = createKey("arisian_planks");
    public static final ResourceKey<Block> ARISIAN_STAIRS = createKey("arisian_stairs");
    public static final ResourceKey<Block> ARISIAN_SLAB = createKey("arisian_slab");
    public static final ResourceKey<Block> ARISIAN_FENCE = createKey("arisian_fence");
    public static final ResourceKey<Block> ARISIAN_FENCE_GATE = createKey("arisian_fence_gate");
    public static final ResourceKey<Block> ARISIAN_DOOR = createKey("arisian_door");
    public static final ResourceKey<Block> ARISIAN_TRAPDOOR = createKey("arisian_trapdoor");
    public static final ResourceKey<Block> ARISIAN_PRESSURE_PLATE = createKey("arisian_pressure_plate");
    public static final ResourceKey<Block> ARISIAN_BUTTON = createKey("arisian_button");
    public static final ResourceKey<Block> ARISIAN_SAPLING = createKey("arisian_sapling");
    public static final ResourceKey<Block> POTTED_ARISIAN_SAPLING = createKey("potted_arisian_sapling");
    public static final ResourceKey<Block> ARISIAN_BOOKSHELF = createKey("arisian_bookshelf");
    public static final ResourceKey<Block> ARISIAN_CRAFTING_TABLE = createKey("arisian_crafting_table");
    public static final ResourceKey<Block> ARISIAN_SIGN = createKey("arisian_sign");
    public static final ResourceKey<Block> ARISIAN_WALL_SIGN = createKey("arisian_wall_sign");
    public static final ResourceKey<Block> ARISIAN_HANGING_SIGN = createKey("arisian_hanging_sign");
    public static final ResourceKey<Block> ARISIAN_WALL_HANGING_SIGN = createKey("arisian_wall_hanging_sign");
    public static final ResourceKey<Block> ARISIAN_LEAVES = createKey("arisian_leaves");

    public static final ResourceKey<Block> THORN_SPROUT = createKey("thorn_sprout");

    public static final ResourceKey<Block> SYTHIAN_NYLIUM = createKey("sythian_nylium");
    public static final ResourceKey<Block> SYTHIAN_SPROUTS = createKey("sythian_sprouts");
    public static final ResourceKey<Block> POTTED_SYTHIAN_SPROUTS = createKey("potted_sythian_sprouts");
    public static final ResourceKey<Block> SYTHIAN_ROOTS = createKey("sythian_roots");
    public static final ResourceKey<Block> POTTED_SYTHIAN_ROOTS = createKey("potted_sythian_roots");
    public static final ResourceKey<Block> SYTHIAN_SOIL = createKey("sythian_soil");
    public static final ResourceKey<Block> SYTHIAN_FARMLAND = createKey("sythian_farmland");
    public static final ResourceKey<Block> HANGING_SYTHIAN_ROOTS = createKey("hanging_sythian_roots");
    public static final ResourceKey<Block> HANGING_SYTHIAN_ROOTS_PLANT = createKey("hanging_sythian_roots_plant");
    public static final ResourceKey<Block> SYTHIAN_WART_BLOCK = createKey("sythian_wart_block");
    public static final ResourceKey<Block> SYTHIAN_SHOOT = createKey("sythian_shoot");
    public static final ResourceKey<Block> SYTHIAN_STALK = createKey("sythian_stalk");
    public static final ResourceKey<Block> POTTED_SYTHIAN_STALK = createKey("potted_sythian_stalk");
    public static final ResourceKey<Block> SYTHIAN_STEM = createKey("sythian_stem");
    public static final ResourceKey<Block> SYTHIAN_HYPHAE = createKey("sythian_hyphae");
    public static final ResourceKey<Block> STRIPPED_SYTHIAN_STEM = createKey("stripped_sythian_stem");
    public static final ResourceKey<Block> STRIPPED_SYTHIAN_HYPHAE = createKey("stripped_sythian_hyphae");
    public static final ResourceKey<Block> SYTHIAN_PLANKS = createKey("sythian_planks");
    public static final ResourceKey<Block> SYTHIAN_STAIRS = createKey("sythian_stairs");
    public static final ResourceKey<Block> SYTHIAN_SLAB = createKey("sythian_slab");
    public static final ResourceKey<Block> SYTHIAN_FENCE = createKey("sythian_fence");
    public static final ResourceKey<Block> SYTHIAN_FENCE_GATE = createKey("sythian_fence_gate");
    public static final ResourceKey<Block> SYTHIAN_DOOR = createKey("sythian_door");
    public static final ResourceKey<Block> SYTHIAN_TRAPDOOR = createKey("sythian_trapdoor");
    public static final ResourceKey<Block> SYTHIAN_PRESSURE_PLATE = createKey("sythian_pressure_plate");
    public static final ResourceKey<Block> SYTHIAN_BUTTON = createKey("sythian_button");
    public static final ResourceKey<Block> SYTHIAN_FUNGUS = createKey("sythian_fungus");
    public static final ResourceKey<Block> POTTED_SYTHIAN_FUNGUS = createKey("potted_sythian_fungus");
    public static final ResourceKey<Block> SYTHIAN_BOOKSHELF = createKey("sythian_bookshelf");
    public static final ResourceKey<Block> SYTHIAN_CRAFTING_TABLE = createKey("sythian_crafting_table");
    public static final ResourceKey<Block> SYTHIAN_SIGN = createKey("sythian_sign");
    public static final ResourceKey<Block> SYTHIAN_WALL_SIGN = createKey("sythian_wall_sign");
    public static final ResourceKey<Block> SYTHIAN_HANGING_SIGN = createKey("sythian_hanging_sign");
    public static final ResourceKey<Block> SYTHIAN_WALL_HANGING_SIGN = createKey("sythian_wall_hanging_sign");
    public static final ResourceKey<Block> SYTHIAN_SCAFFOLDING = createKey("sythian_scaffolding");

    public static final ResourceKey<Block> CRIMSON_BLACKSTONE_NYLIUM = createKey("crimson_blackstone_nylium");
    public static final ResourceKey<Block> TALL_CRIMSON_ROOTS = createKey("tall_crimson_roots");
    public static final ResourceKey<Block> CRIMSON_BERRY_BUSH = createKey("crimson_berry_bush");
    public static final ResourceKey<Block> CRIMSON_CARPET = createKey("crimson_carpet");

    public static final ResourceKey<Block> FUNGAL_BULBS = createKey("fungal_bulbs");

    public static final ResourceKey<Block> PENDORITE_BLOCK = createKey("pendorite_block");
    public static final ResourceKey<Block> PENDORITE_ORE = createKey("pendorite_ore");
    public static final ResourceKey<Block> RAW_PENDORITE_BLOCK = createKey("raw_pendorite_block");
    public static final ResourceKey<Block> CUT_PENDORITE = createKey("cut_pendorite");
    public static final ResourceKey<Block> CUT_PENDORITE_STAIRS = createKey("cut_pendorite_stairs");
    public static final ResourceKey<Block> CUT_PENDORITE_SLAB = createKey("cut_pendorite_slab");
    public static final ResourceKey<Block> CHISELED_PENDORITE = createKey("chiseled_pendorite");
    public static final ResourceKey<Block> PENDORITE_GRATE = createKey("pendorite_grate");
    public static final ResourceKey<Block> PENDORITE_DOOR = createKey("pendorite_door");
    public static final ResourceKey<Block> PENDORITE_TRAPDOOR = createKey("pendorite_trapdoor");
    public static final ResourceKey<Block> PENDORITE_LANTERN = createKey("pendorite_lantern");
    public static final ResourceKey<Block> PENDORITE_TORCH = createKey("pendorite_torch");
    public static final ResourceKey<Block> PENDORITE_WALL_TORCH = createKey("pendorite_wall_torch");
    public static final ResourceKey<Block> PENDORITE_CHAIN = createKey("pendorite_chain");
    public static final ResourceKey<Block> PENDORITE_BARS = createKey("pendorite_bars");
    public static final ResourceKey<Block> PENDORITE_CAMPFIRE = createKey("pendorite_campfire");
    public static final ResourceKey<Block> PENDORITE_FIRE_ROD = createKey("pendorite_fire_rod");

    public static final ResourceKey<Block> SOUL_FIRE_ROD = createKey("soul_fire_rod");
    public static final ResourceKey<Block> BLAZE_FIRE_ROD = createKey("blaze_fire_rod");

    public static final ResourceKey<Block> TALL_CRIMSON_FUNGI = createKey("tall_crimson_fungi");
    public static final ResourceKey<Block> HORNET_NEST = createKey("hornet_nest");
    public static final ResourceKey<Block> BARTERING_TABLE = createKey("bartering_table");

    private static ResourceKey<Block> createKey(String name) {
        return NetherDescent.key(Registries.BLOCK, name);
    }
}
