modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/Potion-Studios/Nether-Descent/issues"
license = "All Rights Reserved"

[[mods]]
modId = "netherdescent"
version = "${version}"
displayName = "Nether Descent"
logoFile = "netherdescent.png"
authors = "Joseph T. McQuigg (JT122406), AOCAWOL"
description = '''
Nether Descent is a brand new nether biome mod by the Potion Studios team, truly an adventure like no other awaits you with new biomes, mobs, blocks, items, and more!
'''
displayURL="https://potionstudios.net/"

[[dependencies.netherdescent]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.netherdescent]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.netherdescent]]
modId = "ohthetreesyoullgrow"
type = "required"
versionRange = "[6.1.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.netherdescent]]
modId = "terrablender"
type = "optional"
versionRange = "[4.3.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.netherdescent]]
modId = "biolith"
type = "optional"
versionRange = "[3.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "netherdescent-common.mixins.json"
